# Generated by Django 4.1.3 on 2022-12-04 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='banner.jpg', upload_to=''),
        ),
    ]
