# Generated by Django 4.1.3 on 2022-12-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0002_alter_user_avatar_alter_user_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='oven.png', upload_to=''),
        ),
    ]
