# Generated by Django 4.1.3 on 2022-12-04 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0004_remove_post_thumbnail_comment_image_post_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
