# Generated by Django 4.1.3 on 2022-12-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breddit', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
